parameters:
    pim_connector.array_converter.flat.attribute_option.class:                   Pim\Component\Connector\ArrayConverter\Flat\AttributeOptionStandardConverter
    pim_connector.array_converter.flat.attribute.class:                          Pim\Component\Connector\ArrayConverter\Flat\AttributeStandardConverter
    pim_connector.array_converter.structured.attribute_option.class:             Pim\Component\Connector\ArrayConverter\Structured\AttributeOptionStandardConverter
    pim_connector.array_converter.flat.product.class:                            Pim\Component\Connector\ArrayConverter\Flat\ProductStandardConverter
    pim_connector.array_converter.flat.product_association.class:                Pim\Component\Connector\ArrayConverter\Flat\ProductAssociationStandardConverter

    pim_connector.array_converter.flat.product.registry.class:                   Pim\Component\Connector\ArrayConverter\Flat\Product\Converter\ValueConverterRegistry
    pim_connector.array_converter.flat.product.abstract.class:                   Pim\Component\Connector\ArrayConverter\Flat\Product\Converter\AbstractValueConverter
    pim_connector.array_converter.flat.product.price.class:                      Pim\Component\Connector\ArrayConverter\Flat\Product\Converter\PriceConverter
    pim_connector.array_converter.flat.product.metric.class:                     Pim\Component\Connector\ArrayConverter\Flat\Product\Converter\MetricConverter
    pim_connector.array_converter.flat.product.multiselect.class:                Pim\Component\Connector\ArrayConverter\Flat\Product\Converter\MultiSelectConverter
    pim_connector.array_converter.flat.product.simpleselect.class:               Pim\Component\Connector\ArrayConverter\Flat\Product\Converter\SimpleSelectConverter
    pim_connector.array_converter.flat.product.media.class:                      Pim\Component\Connector\ArrayConverter\Flat\Product\Converter\MediaConverter
    pim_connector.array_converter.flat.product.scalar.class:                     Pim\Component\Connector\ArrayConverter\Flat\Product\Converter\ScalarConverter
    pim_connector.array_converter.flat.product.field.class:                      Pim\Component\Connector\ArrayConverter\Flat\Product\Converter\ProductFieldConverter

    # TODO: rename following services
    pim_connector.array_converter.flat.attribute_field_extractor.class:          Pim\Component\Connector\ArrayConverter\Flat\Product\Extractor\ProductAttributeFieldExtractor
    pim_connector.array_converter.flat.attribute_field_resolver.class:           Pim\Component\Connector\ArrayConverter\Flat\Product\Resolver\AttributeColumnsResolver
    pim_connector.array_converter.flat.association_field_resolver.class:         Pim\Component\Connector\ArrayConverter\Flat\Product\Resolver\AssociationColumnsResolver
    pim_connector.array_converter.splitter.field.class:                          Pim\Component\Connector\ArrayConverter\Flat\Product\Splitter\FieldSplitter
    pim_connector.array_converter.merger.columns.class:                          Pim\Component\Connector\ArrayConverter\Flat\Product\Merger\ColumnsMerger
    pim_connector.array_converter.flat.variant_group.class:                      Pim\Component\Connector\ArrayConverter\Flat\VariantGroupStandardConverter
    pim_connector.array_converter.mapper.columns.class:                          Pim\Component\Connector\ArrayConverter\Flat\Product\Mapper\ColumnsMapper

services:
    # array converters
    pim_connector.array_converter.flat.attribute_option:
        class: %pim_connector.array_converter.flat.attribute_option.class%
        arguments:
            - '@pim_catalog.repository.locale'

    pim_connector.array_converter.flat.attribute:
        class: %pim_connector.array_converter.flat.attribute.class%

    pim_connector.array_converter.structured.attribute_option:
        class: %pim_connector.array_converter.structured.attribute_option.class%

    pim_connector.array_converter.flat.product:
        class: %pim_connector.array_converter.flat.product.class%
        arguments:
            - '@pim_connector.array_converter.flat.attribute_field_extractor'
            - '@pim_connector.array_converter.flat.product.registry'
            - '@pim_connector.array_converter.flat.association_field_resolver'
            - '@pim_connector.array_converter.flat.attribute_field_resolver'
            - '@pim_connector.array_converter.flat.product.field'
            - '@pim_connector.array_converter.merger.columns'
            - '@pim_connector.array_converter.mapper.columns'

    pim_connector.array_converter.flat.product_association:
        class: %pim_connector.array_converter.flat.product_association.class%
        arguments:
            - '@pim_connector.array_converter.flat.product'
            - '@pim_connector.array_converter.flat.association_field_resolver'
            - '@pim_connector.array_converter.flat.attribute_field_resolver'

    pim_connector.array_converter.flat.variant_group:
        class: %pim_connector.array_converter.flat.variant_group.class%
        arguments:
            - '@pim_catalog.repository.locale'
            - '@pim_catalog.repository.attribute'
            - '@pim_connector.array_converter.flat.product'

    # extractors
    pim_connector.array_converter.flat.attribute_field_extractor:
        class: %pim_connector.array_converter.flat.attribute_field_extractor.class%
        arguments:
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.locale'

    # product flat converters (attributes, fields)
    pim_connector.array_converter.flat.product.registry:
        class: %pim_connector.array_converter.flat.product.registry.class%

    pim_connector.array_converter.flat.product.abstract:
        class: %pim_connector.array_converter.flat.product.abstract.class%
        arguments:
            - '@pim_connector.array_converter.splitter.field'

    pim_connector.array_converter.flat.product.price:
        class: %pim_connector.array_converter.flat.product.price.class%
        parent: pim_connector.array_converter.flat.product.abstract
        arguments:
            - ['pim_catalog_price_collection']
        tags:
            - { name: 'pim_connector.array_converter.flat.product_value' }

    pim_connector.array_converter.flat.product.metric:
        class: %pim_connector.array_converter.flat.product.metric.class%
        parent: pim_connector.array_converter.flat.product.abstract
        arguments:
            - ['pim_catalog_metric']
        tags:
            - { name: 'pim_connector.array_converter.flat.product_value' }

    pim_connector.array_converter.flat.product.multiselect:
        class: %pim_connector.array_converter.flat.product.multiselect.class%
        parent: pim_connector.array_converter.flat.product.abstract
        arguments:
            - ['pim_catalog_multiselect', 'pim_reference_data_multiselect']
        tags:
            - { name: 'pim_connector.array_converter.flat.product_value' }

    pim_connector.array_converter.flat.product.simpleselect:
        class: %pim_connector.array_converter.flat.product.simpleselect.class%
        parent: pim_connector.array_converter.flat.product.abstract
        arguments:
            - ['pim_catalog_simpleselect', 'pim_reference_data_simpleselect']
        tags:
            - { name: 'pim_connector.array_converter.flat.product_value' }

    pim_connector.array_converter.flat.product.scalar:
        class: %pim_connector.array_converter.flat.product.scalar.class%
        parent: pim_connector.array_converter.flat.product.abstract
        arguments:
            - ['pim_catalog_identifier', 'pim_catalog_text', 'pim_catalog_textarea', 'pim_catalog_date', 'pim_catalog_boolean', 'pim_catalog_number']
        tags:
            - { name: 'pim_connector.array_converter.flat.product_value' }

    pim_connector.array_converter.flat.product.media:
        class: %pim_connector.array_converter.flat.product.media.class%
        parent: pim_connector.array_converter.flat.product.abstract
        arguments:
            - ['pim_catalog_image', 'pim_catalog_file']
        tags:
            - { name: 'pim_connector.array_converter.flat.product_value' }

    pim_connector.array_converter.flat.product.field:
        class: %pim_connector.array_converter.flat.product.field.class%
        arguments:
            - '@pim_connector.array_converter.splitter.field'
            - '@pim_connector.array_converter.flat.association_field_resolver'

    # resolvers
    pim_connector.array_converter.flat.attribute_field_resolver:
        class: %pim_connector.array_converter.flat.attribute_field_resolver.class%
        arguments:
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.repository.currency'
            - '@pim_catalog.resolver.attribute_values'

    pim_connector.array_converter.flat.association_field_resolver:
        class: %pim_connector.array_converter.flat.association_field_resolver.class%
        arguments:
            - '@pim_catalog.repository.association_type'

    # splitters
    pim_connector.array_converter.splitter.field:
        class: %pim_connector.array_converter.splitter.field.class%

    # mergers
    pim_connector.array_converter.merger.columns:
        class: %pim_connector.array_converter.merger.columns.class%
        arguments:
            - '@pim_connector.array_converter.flat.attribute_field_extractor'

    # mappers
    pim_connector.array_converter.mapper.columns:
        class: %pim_connector.array_converter.mapper.columns.class%
